"""Add worker_id and priority columns to analysis_tasks

Revision ID: 948bd2504849
Revises: 
Create Date: 2025-04-30 15:51:29.067307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '948bd2504849'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_tasks', sa.Column('worker_id', sa.String(length=100), nullable=True))
    op.add_column('analysis_tasks', sa.Column('priority', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analysis_tasks', 'priority')
    op.drop_column('analysis_tasks', 'worker_id')
    # ### end Alembic commands ###
