[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ai-project-analyzer-core"
version = "0.1.0"
description = "Core business logic for AI Project Analyzer"
readme = "README.md"
requires-python = ">=3.11"
license = "MIT"
authors = [
    {name = "Your Name", email = "your.email@example.com"}
]
dependencies = [
    "langchain>=0.1.0",
    "langchain-google-genai>=1.0.0",
    "python-dotenv>=1.0.0",
    "gitingest>=0.1.12",
    "rich>=13.0.0",
    "loguru>=0.7.0",
    "PyGithub>=1.59.0",
    "pandas>=2.0.0",
    "openpyxl>=3.1.0",
]

[tool.ruff]
line-length = 100
target-version = "py311"

# Package-specific development dependencies (shared ones are in workspace root)
[project.optional-dependencies]
dev = [
    # Add package-specific dev dependencies here if needed
] 