[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ai-project-analyzer-cli"
version = "0.1.0"
description = "Command-line interface for AI Project Analyzer"
readme = "README.md"
requires-python = ">=3.11"
license = "MIT"
authors = [
    {name = "Your Name", email = "your.email@example.com"}
]
dependencies = [
    # CLI-specific dependencies
    "typer>=0.9.0",
    "rich>=13.0.0",
    # Core package dependencies will be managed via PYTHONPATH
    "langchain>=0.1.0",
    "langchain-google-genai>=1.0.0",
    "python-dotenv>=1.0.0",
    "gitingest>=0.1.4",
    "loguru>=0.7.0",
    "PyGithub>=1.59.0",
    "pandas>=2.0.0",
    "openpyxl>=3.1.0",
]

[project.scripts]
analyze = "src.cli:app"

[tool.ruff]
line-length = 100
target-version = "py311"

[tool.pytest.ini_options]
asyncio_default_fixture_loop_scope = "function"
asyncio_mode = "auto"

# Package-specific development dependencies (shared ones are in workspace root)
[project.optional-dependencies]
dev = [
    # Add CLI-specific dev dependencies here if needed
] 